Neos:

  ContentRepository:

    # Configure available content dimensions for nodes, after adding a dimension the database has to be filled with
    # the dimension default values.
    # Also add named presets with fallback chains that can happen in your dimensions.
    #
    # Example
    #
    #   contentDimensions:
    #     language:
    #       default: mul_ZZ
    #       defaultPreset: 'all'
    #       presets:
    #         'all':
    #           values: ['mul_ZZ']
    #
    #     persona:
    #       default: everybody
    #       defaultPreset: 'all'
    #       presets:
    #         'all':
    #           values: ['everybody']
    contentDimensions: {  }

    # Configures defaults for node label generation
    labelGenerator:
      eel:
        defaultContext:
          String: Neos\Eel\Helper\StringHelper
          Array: Neos\Eel\Helper\ArrayHelper
          Date: Neos\Eel\Helper\DateHelper
          Configuration: Neos\Eel\Helper\ConfigurationHelper
          Math: Neos\Eel\Helper\MathHelper
          Json: Neos\Eel\Helper\JsonHelper
          I18n: Neos\Flow\I18n\EelHelper\TranslationHelper
          q: Neos\Eel\FlowQuery\FlowQuery::q

    # the fallback NodeType can be used as a replacement for unknown NodeTypes
    #
    # Example
    #
    #  fallbackNodeType: 'Some.Package:SomeNodeType'
    fallbackNodeType: null

    unstableInternalWillChangeLater:
      testing:
        projectorsToBeReset: {}
        # DoctrineDbal: Neos\ContentGraph\DoctrineDbalAdapter\Domain\Repository\ContentGraph
        activeContentGraphs: {}
      projection:
        defaultProjectorsToBeBlocked:
          'Neos\ContentRepository\Domain\Projection\ContentStream\ContentStreamProjector': true
          'Neos\ContentRepository\Domain\Projection\Workspace\WorkspaceProjector': true
    nodeAccessorFactories:
      contentSubgraph:
        position: end
        className: Neos\ContentRepository\NodeAccess\Implementation\ContentSubgraphAccessorFactory

    propertyConverters:
      ScalarNormalizer:
        className: Neos\ContentRepository\Infrastructure\Property\Normalizer\ScalarNormalizer
      ArrayNormalizer:
        className: Neos\ContentRepository\Infrastructure\Property\Normalizer\ArrayNormalizer
      DateTimeNormalizer:
        className: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        position: 'start'
      UriNormalizer:
        className: Neos\ContentRepository\Infrastructure\Property\Normalizer\UriNormalizer
      ValueObjectArrayDenormalizer:
        className: Neos\ContentRepository\Infrastructure\Property\Normalizer\ValueObjectArrayDenormalizer
      ValueObjectBoolDenormalizer:
        className: Neos\ContentRepository\Infrastructure\Property\Normalizer\ValueObjectBoolDenormalizer
      ValueObjectFloatDenormalizer:
        className: Neos\ContentRepository\Infrastructure\Property\Normalizer\ValueObjectFloatDenormalizer
      ValueObjectIntDenormalizer:
        className: Neos\ContentRepository\Infrastructure\Property\Normalizer\ValueObjectIntDenormalizer
      ValueObjectStringDenormalizer:
        className: Neos\ContentRepository\Infrastructure\Property\Normalizer\ValueObjectStringDenormalizer
      DoctrinePersistentObjectNormalizer:
        className: Neos\ContentRepository\Infrastructure\Property\Normalizer\DoctrinePersistentObjectNormalizer
      CollectionTypeDenormalizer:
        className: Neos\ContentRepository\Infrastructure\Property\Normalizer\CollectionTypeDenormalizer
      ProxyAwareObjectNormalizer:
        className: Neos\EventSourcing\EventStore\Normalizer\ProxyAwareObjectNormalizer
